### ISSUE TITLE
Product images not displaying in README.md in v1.0

### ISSUE THREAD

**Issue by FredrikFolkeryd** [IKEA/IKEA3DAssemblyDataset#2]
**Expected**
Product images included in the README.md in v1.0 display as images, not links.

**Actual**
The images of products included display as links to git-lfs entities.

**Steps**
Open [README.md](https://github.com/IKEA/IKEA3DAssemblyDataset/blob/main/README.md)

**Screenshot** 
![image](https://user-images.githubusercontent.com/687726/143210847-096021f7-d3d5-4717-8ce6-faaf2beaf6c3.png)

**Comment by TnyPny** [comment]
@FredrikFolkeryd Thanks for submitting this issues. We have fixed the display of images now.
