### ISSUE TITLE
IKEA Object State Dataset - RGBD Videos

### ISSUE THREAD

**Issue by kumarabhinav04** [IKEA/IKEA3DAssemblyDataset#7]
Could you please provide the link to access the  RGBD videos of the assembly process, the 6DoF pose of furniture parts and their bounding box.

**Comment by ogmasoul3d** [comment]
I am not sure what you are referring to. This project only contains gltf files of 5 ikea products.. separated and split into parts to simplify the process of creating training data from 3d.

Are you sure you are looking for the right github project.. I see there are some other projects out there that seems to focus on video and RGBD data.

**Comment by ogmasoul3d** [comment]
Yes the 3d models in this repository were initially created to support the creation of a paper. The paper referred to is not created by IKEA but Yongzhi Su and Mingxin Liu and Jason Rambach and Didier Stricker.

The result of that paper and code, video, and refined assets should be added here when they are done:
https://github.com/mxllmx/IKEAObjectStateDataset

The plan for the IKEAAssemblyDataset repo is that it will only contain 3D models that are split into parts so they can be used for research.

**Comment by suyz526** [comment]
> In citation section, you have mentioned This dataset first appeared in the paper IKEA Object State Dataset: A 6DoF object pose estimation dataset and benchmark for multi-state assembly objects. You can download the RGBD video of the assembly process, the 6DoF pose of furniture parts and their bounding box from [IKEAObjectStateDataset](https://github.com/mxllmx/IKEAObjectStateDataset).
> 
> But there is no link to download the RGBD videos



Further discussion about this topic please refer to [https://github.com/mxllmx/IKEAObjectStateDataset/issues/1](https://github.com/mxllmx/IKEAObjectStateDataset/issues/1)
