### ISSUE TITLE
Correct .pdfs in relation to asset folder

### ISSUE THREAD

**Issue by TnyPny** [IKEA/IKEA3DAssemblyDataset#9]
There are slight construction difference between the BEKVÄM Step stool 3D assets (![BEKVAMdifferences](https://github.com/user-attachments/assets/17ef1874-6910-4e79-aa80-f11458992565)).

There was a mix-up in which assembly instruction .pdf document was distributed.

Article 30178884 should use assembly document AA-444158-09.pdf as we mentioned in the .readme file at the time of the release of the dataset in 2021. However the wrong .pdf (AA-323406-7.pdf) was shared in the folder for 30178884. The most recent version of assembly document for this article shared to customer on IKEA.com is AA-444158-10.pdf, but this should not be used, since it might not fully correspond to the model that was shared in 2021.**Action suggested:
** Remove the incorrect .pdf and add AA-444158-09.pdf.
 
Article 40463852 should use assembly document AA-323406-7.pdf, as stated in the .readme file at the time of the release of the dataset in 2021, but this file was never added to the right folder.
**Action suggested:** Add AA-323406-7.pdf to a pdf_documentation folder for 40463852.

**Comment by jonAspeheim** [comment]
Can be closed now as per commit: 12644d68e06dd1314a2db9960c421b7c2b428b6a

**Comment by jonAspeheim** [comment]
Closing ticket.
